### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by drancope** [TheShark9990/TheShark9990.github.io#2]
Para cambiar el tamaño de las imágenes se pueden añadir los parámetros height y width dentro de la etiqueta de <code>&lt;img&gt;</code>. Así:
<code>&lt;img width="50%" src="loqesea.png"&gt;</code>

**Comment by TheShark9990** [comment]
Lo sé, accidentalmente eliminé el parámetro y me dí cuenta de que era el tamaño deseado, por eso lo quité.

**Comment by TheShark9990** [comment]
Tamaño de las imágenes ajustado a la página real.
